
# .github/workflows/basic_test.yml
name: norminette
on: [push]

jobs:
  make_test:
    runs-on: macos-latest
    name: 42 Make Test
    steps:
    - uses: actions/checkout@v2
    - name: Check basic Makefile jobs
      run: make && make re && make clean && make all && make fclean